# -*- coding: utf-8 -*-
"""Блок 1 «Алгебра»: продвинутый раздел «Инструментарий» / "The Toolkit", RU+EN.
Шесть приёмов, по два разбора AMC-уровня #12–18 на каждый. Изучается ПОСЛЕ короткого курса."""

def F(a, b):
    return f'<span class="frac"><span>{a}</span><span>{b}</span></span>'

TOOLKIT = {
 'items': [

 # ── И1 / T1 ──────────────────────────────────────────────────────────
 {'id': 'И1', 'id_en': 'T1', 'anchor': 'tk1', 'minutes': 15,
  'title': {'ru': 'Симметрия и замена',
            'en': 'Symmetry and Substitution'},
  'intro': {
   'ru': 'Если выражение не меняется при замене <var>x</var> &rarr; 1/<var>x</var> или при перестановке <var>x</var> &harr; <var>y</var> &mdash; не решайте его &laquo;в лоб&raquo;, а введите симметричные переменные: <var>s</var> = <var>x</var> + 1/<var>x</var> для цепочек степеней, <var>s</var> = <var>x</var> + <var>y</var> и <var>p</var> = <var>xy</var> для симметричных систем. Сигналы в условии: пары <var>x</var><sup><var>n</var></sup> + 1/<var>x</var><sup><var>n</var></sup>, выражения, где <var>x</var> и <var>y</var> входят одинаково, просьба найти не сами корни, а их комбинацию.',
   'en': 'If an expression is unchanged by the swap <var>x</var> &rarr; 1/<var>x</var> or by exchanging <var>x</var> &harr; <var>y</var>, do not attack it head-on: introduce symmetric variables instead &mdash; <var>s</var> = <var>x</var> + 1/<var>x</var> for power chains, <var>s</var> = <var>x</var> + <var>y</var> and <var>p</var> = <var>xy</var> for symmetric systems. Signals in the statement: pairs <var>x</var><sup><var>n</var></sup> + 1/<var>x</var><sup><var>n</var></sup>, expressions where <var>x</var> and <var>y</var> enter identically, a question that asks for a combination of the unknowns rather than the unknowns themselves.'},
  'probs': [
   {'tag': {'ru': 'Задача 1 · цепочка степеней', 'en': 'Problem 1 · power chain'},
    'q': {'ru': 'Действительное число <var>x</var> удовлетворяет равенству <var>x</var> + 1/<var>x</var> = 3. Чему равно <var>x</var><sup>5</sup> + 1/<var>x</var><sup>5</sup>?',
          'en': 'A real number <var>x</var> satisfies <var>x</var> + 1/<var>x</var> = 3. What is <var>x</var><sup>5</sup> + 1/<var>x</var><sup>5</sup>?'},
    'sol': {'ru': 'Тупик, в который тянет: решить квадратное уравнение <var>x</var><sup>2</sup> &minus; 3<var>x</var> + 1 = 0, получить <var>x</var> = (3&nbsp;&plusmn;&nbsp;&radic;5)/2 и возводить иррациональность в пятую степень. Это минут десять и почти гарантированная арифметическая ошибка. Приём: обозначим <var>s</var><sub><var>n</var></sub> = <var>x</var><sup><var>n</var></sup> + 1/<var>x</var><sup><var>n</var></sup>. Умножение на <var>s</var><sub>1</sub> даёт рекурсию: <var>s</var><sub><var>n</var></sub>&nbsp;&middot;&nbsp;<var>s</var><sub>1</sub> = <var>s</var><sub><var>n</var>+1</sub> + <var>s</var><sub><var>n</var>&minus;1</sub>, то есть <var>s</var><sub><var>n</var>+1</sub> = 3<var>s</var><sub><var>n</var></sub> &minus; <var>s</var><sub><var>n</var>&minus;1</sub>. Стартуем: <var>s</var><sub>1</sub> = 3; <var>s</var><sub>2</sub> = 3<sup>2</sup> &minus; 2 = 7. Дальше по цепочке: <var>s</var><sub>3</sub> = 3&nbsp;&middot;&nbsp;7 &minus; 3 = 18; <var>s</var><sub>4</sub> = 3&nbsp;&middot;&nbsp;18 &minus; 7 = 47; <var>s</var><sub>5</sub> = 3&nbsp;&middot;&nbsp;47 &minus; 18 = <b>123</b>. Четыре умножения в уме &mdash; и никаких радикалов.',
           'en': 'The dead end that beckons: solve the quadratic <var>x</var><sup>2</sup> &minus; 3<var>x</var> + 1 = 0, get <var>x</var> = (3&nbsp;&plusmn;&nbsp;&radic;5)/2, and raise the irrationality to the fifth power. That is ten minutes and an almost guaranteed arithmetic slip. The trick: write <var>s</var><sub><var>n</var></sub> = <var>x</var><sup><var>n</var></sup> + 1/<var>x</var><sup><var>n</var></sup>. Multiplying by <var>s</var><sub>1</sub> gives a recursion: <var>s</var><sub><var>n</var></sub>&nbsp;&middot;&nbsp;<var>s</var><sub>1</sub> = <var>s</var><sub><var>n</var>+1</sub> + <var>s</var><sub><var>n</var>&minus;1</sub>, that is <var>s</var><sub><var>n</var>+1</sub> = 3<var>s</var><sub><var>n</var></sub> &minus; <var>s</var><sub><var>n</var>&minus;1</sub>. Start: <var>s</var><sub>1</sub> = 3; <var>s</var><sub>2</sub> = 3<sup>2</sup> &minus; 2 = 7. Then walk the chain: <var>s</var><sub>3</sub> = 3&nbsp;&middot;&nbsp;7 &minus; 3 = 18; <var>s</var><sub>4</sub> = 3&nbsp;&middot;&nbsp;18 &minus; 7 = 47; <var>s</var><sub>5</sub> = 3&nbsp;&middot;&nbsp;47 &minus; 18 = <b>123</b>. Four mental multiplications and not a radical in sight.'}},
   {'tag': {'ru': 'Задача 2 · симметричная система', 'en': 'Problem 2 · symmetric system'},
    'q': {'ru': 'Действительные числа <var>x</var> и <var>y</var> удовлетворяют системе <var>x</var> + <var>y</var> + <var>xy</var> = 11 и <var>x</var><sup>2</sup><var>y</var> + <var>xy</var><sup>2</sup> = 30. Чему равна сумма всех возможных значений выражения <var>x</var><sup>2</sup> + <var>y</var><sup>2</sup>?',
          'en': 'Real numbers <var>x</var> and <var>y</var> satisfy <var>x</var> + <var>y</var> + <var>xy</var> = 11 and <var>x</var><sup>2</sup><var>y</var> + <var>xy</var><sup>2</sup> = 30. What is the sum of all possible values of <var>x</var><sup>2</sup> + <var>y</var><sup>2</sup>?'},
    'sol': {'ru': 'Тупик: выразить <var>y</var> через <var>x</var> из первого уравнения и подставить во второе &mdash; получится уравнение четвёртой степени. Приём: оба уравнения симметричны, значит вводим <var>s</var> = <var>x</var> + <var>y</var>, <var>p</var> = <var>xy</var>. Первое уравнение: <var>s</var> + <var>p</var> = 11. Второе: <var>x</var><sup>2</sup><var>y</var> + <var>xy</var><sup>2</sup> = <var>xy</var>(<var>x</var> + <var>y</var>) = <var>sp</var> = 30. Итак, <var>s</var> и <var>p</var> &mdash; корни уравнения <var>t</var><sup>2</sup> &minus; 11<var>t</var> + 30 = 0, то есть {5;&nbsp;6}: либо <var>s</var> = 5, <var>p</var> = 6, либо <var>s</var> = 6, <var>p</var> = 5. Проверяем существование действительных <var>x</var>, <var>y</var>: нужно <var>s</var><sup>2</sup> &ge; 4<var>p</var>; для (5;&nbsp;6): 25 &ge; 24 &mdash; да; для (6;&nbsp;5): 36 &ge; 20 &mdash; да. Тогда <var>x</var><sup>2</sup> + <var>y</var><sup>2</sup> = <var>s</var><sup>2</sup> &minus; 2<var>p</var>: в первом случае 25 &minus; 12 = 13, во втором 36 &minus; 10 = 26. Сумма возможных значений: 13 + 26 = <b>39</b>.',
           'en': 'The dead end: solve the first equation for <var>y</var> and substitute into the second &mdash; a quartic appears. The trick: both equations are symmetric, so introduce <var>s</var> = <var>x</var> + <var>y</var>, <var>p</var> = <var>xy</var>. First equation: <var>s</var> + <var>p</var> = 11. Second: <var>x</var><sup>2</sup><var>y</var> + <var>xy</var><sup>2</sup> = <var>xy</var>(<var>x</var> + <var>y</var>) = <var>sp</var> = 30. So <var>s</var> and <var>p</var> are the roots of <var>t</var><sup>2</sup> &minus; 11<var>t</var> + 30 = 0, that is {5,&nbsp;6}: either <var>s</var> = 5, <var>p</var> = 6, or <var>s</var> = 6, <var>p</var> = 5. Check that real <var>x</var>, <var>y</var> exist: we need <var>s</var><sup>2</sup> &ge; 4<var>p</var>; for (5,&nbsp;6): 25 &ge; 24 &mdash; yes; for (6,&nbsp;5): 36 &ge; 20 &mdash; yes. Then <var>x</var><sup>2</sup> + <var>y</var><sup>2</sup> = <var>s</var><sup>2</sup> &minus; 2<var>p</var>: 25 &minus; 12 = 13 in the first case and 36 &minus; 10 = 26 in the second. The sum of the possible values is 13 + 26 = <b>39</b>.'}},
  ]},

 # ── И2 / T2 ──────────────────────────────────────────────────────────
 {'id': 'И2', 'id_en': 'T2', 'anchor': 'tk2', 'minutes': 15,
  'title': {'ru': 'Телескопирование и группировка',
            'en': 'Telescoping and Grouping'},
  'intro': {
   'ru': 'Длинная сумма или длинное произведение с многоточием &mdash; почти всегда не про терпение, а про схлопывание: каждый член раскладывается в разность (или отношение) соседних величин, и середина взаимно уничтожается. Сигналы: знаменатели вида <var>n</var>(<var>n</var> + <var>k</var>), множители вида 1 &minus; 1/<var>n</var><sup>2</sup>, сумма с &laquo;&hellip;&raquo; на десятки членов. Первый шаг всегда один: распишите два-три члена и посмотрите, что сокращается.',
   'en': 'A long sum or product with an ellipsis is almost never about patience &mdash; it is about collapse: each term splits into a difference (or ratio) of neighboring quantities, and the middle cancels itself out. Signals: denominators of the form <var>n</var>(<var>n</var> + <var>k</var>), factors like 1 &minus; 1/<var>n</var><sup>2</sup>, a sum with &ldquo;&hellip;&rdquo; spanning dozens of terms. The first move is always the same: write out two or three terms and watch what cancels.'},
  'probs': [
   {'tag': {'ru': 'Задача 1 · телескопическая сумма', 'en': 'Problem 1 · telescoping sum'},
    'q': {'ru': f'Чему равна сумма {F("1","1&middot;3")} + {F("1","2&middot;4")} + {F("1","3&middot;5")} + &hellip; + {F("1","24&middot;26")}?',
          'en': f'What is the sum {F("1","1&middot;3")} + {F("1","2&middot;4")} + {F("1","3&middot;5")} + &hellip; + {F("1","24&middot;26")}?'},
    'sol': {'ru': f'Тупик: приводить 24 дроби к общему знаменателю. Приём: разложим общий член. Из {F("1","<var>n</var>(<var>n</var> + 2)")} = {F("1","2")}({F("1","<var>n</var>")} &minus; {F("1","<var>n</var> + 2")}) сумма превращается в {F("1","2")}(1 &minus; {F("1","3")} + {F("1","2")} &minus; {F("1","4")} + {F("1","3")} &minus; {F("1","5")} + &hellip;). Здесь шаг равен 2, поэтому выживают ДВА первых положительных члена и ДВА последних отрицательных &mdash; это главное место для ошибки: сокращается не &laquo;всё, кроме первого и последнего&raquo;. Остаётся {F("1","2")}(1 + {F("1","2")} &minus; {F("1","25")} &minus; {F("1","26")}) = {F("1","2")}&nbsp;&middot;&nbsp;{F("462","325")} = <b>{F("231","325")}</b>. Прикидка для контроля: ответ чуть меньше 3/4 &mdash; ровно как и должно быть, ведь полная бесконечная сумма равна 3/4.',
           'en': f'The dead end: put 24 fractions over a common denominator. The trick: split the general term. From {F("1","<var>n</var>(<var>n</var> + 2)")} = {F("1","2")}({F("1","<var>n</var>")} &minus; {F("1","<var>n</var> + 2")}) the sum becomes {F("1","2")}(1 &minus; {F("1","3")} + {F("1","2")} &minus; {F("1","4")} + {F("1","3")} &minus; {F("1","5")} + &hellip;). The gap is 2, so TWO leading positive terms and TWO trailing negative terms survive &mdash; the classic error is assuming &ldquo;everything but the first and last&rdquo; cancels. What remains is {F("1","2")}(1 + {F("1","2")} &minus; {F("1","25")} &minus; {F("1","26")}) = {F("1","2")}&nbsp;&middot;&nbsp;{F("462","325")} = <b>{F("231","325")}</b>. Sanity check: the answer is slightly under 3/4 &mdash; exactly right, since the full infinite sum equals 3/4.'}},
   {'tag': {'ru': 'Задача 2 · схлопывающееся произведение', 'en': 'Problem 2 · collapsing product'},
    'q': {'ru': f'Чему равно произведение (1 &minus; {F("1","2<sup>2</sup>")})(1 &minus; {F("1","3<sup>2</sup>")})(1 &minus; {F("1","4<sup>2</sup>")})&nbsp;&middot;&nbsp;&hellip;&nbsp;&middot;&nbsp;(1 &minus; {F("1","50<sup>2</sup>")})?',
          'en': f'What is the product (1 &minus; {F("1","2<sup>2</sup>")})(1 &minus; {F("1","3<sup>2</sup>")})(1 &minus; {F("1","4<sup>2</sup>")})&nbsp;&middot;&nbsp;&hellip;&nbsp;&middot;&nbsp;(1 &minus; {F("1","50<sup>2</sup>")})?'},
    'sol': {'ru': f'Тупик: перемножать десятичные приближения &mdash; произведение 49 множителей руками не взять. Приём: каждый множитель &mdash; разность квадратов: 1 &minus; {F("1","<var>k</var><sup>2</sup>")} = {F("(<var>k</var> &minus; 1)(<var>k</var> + 1)","<var>k</var><sup>2</sup>")}. Произведение распадается на две бегущие цепочки: {F("1&middot;3","2&middot;2")}&nbsp;&middot;&nbsp;{F("2&middot;4","3&middot;3")}&nbsp;&middot;&nbsp;{F("3&middot;5","4&middot;4")}&nbsp;&middot;&nbsp;&hellip;&nbsp;&middot;&nbsp;{F("49&middot;51","50&middot;50")}. Цепочка &laquo;<var>k</var> &minus; 1&raquo; даёт 1&middot;2&middot;3&middot;&hellip;&middot;49, цепочка &laquo;<var>k</var> + 1&raquo; даёт 3&middot;4&middot;&hellip;&middot;51, знаменатель &mdash; (2&middot;3&middot;&hellip;&middot;50)<sup>2</sup>. Почти всё сокращается, выживают края: {F("1","2")}&nbsp;&middot;&nbsp;{F("51","50")} = <b>{F("51","100")}</b>. Запомните общий вид: до <var>n</var> произведение равно (<var>n</var> + 1)/(2<var>n</var>) &mdash; чуть больше половины, и это мгновенная проверка ответа.',
           'en': f'The dead end: multiply decimal approximations &mdash; 49 factors will not yield to brute force. The trick: each factor is a difference of squares: 1 &minus; {F("1","<var>k</var><sup>2</sup>")} = {F("(<var>k</var> &minus; 1)(<var>k</var> + 1)","<var>k</var><sup>2</sup>")}. The product splits into two running chains: {F("1&middot;3","2&middot;2")}&nbsp;&middot;&nbsp;{F("2&middot;4","3&middot;3")}&nbsp;&middot;&nbsp;{F("3&middot;5","4&middot;4")}&nbsp;&middot;&nbsp;&hellip;&nbsp;&middot;&nbsp;{F("49&middot;51","50&middot;50")}. The &ldquo;<var>k</var> &minus; 1&rdquo; chain gives 1&middot;2&middot;3&middot;&hellip;&middot;49, the &ldquo;<var>k</var> + 1&rdquo; chain gives 3&middot;4&middot;&hellip;&middot;51, and the denominator is (2&middot;3&middot;&hellip;&middot;50)<sup>2</sup>. Nearly everything cancels; only the edges survive: {F("1","2")}&nbsp;&middot;&nbsp;{F("51","50")} = <b>{F("51","100")}</b>. Remember the general shape: up to <var>n</var> the product is (<var>n</var> + 1)/(2<var>n</var>) &mdash; just over one half, which is an instant sanity check.'}},
  ]},

 # ── И3 / T3 ──────────────────────────────────────────────────────────
 {'id': 'И3', 'id_en': 'T3', 'anchor': 'tk3', 'minutes': 15,
  'title': {'ru': 'Разность квадратов и умные факторизации',
            'en': 'Difference of Squares and Clever Factoring'},
  'intro': {
   'ru': 'Уравнение в целых числах с произведением переменных, или огромное число вида <var>a</var><sup>4</sup> + 4<var>b</var><sup>4</sup>, &mdash; сигнал, что задачу решает факторизация, а не вычисление. Два рабочих инструмента: приём Симона (добавить константу, чтобы <var>xy</var> + <var>ax</var> + <var>by</var> сложилось в произведение двух скобок) и тождество Софи Жермен: <var>a</var><sup>4</sup> + 4<var>b</var><sup>4</sup> = (<var>a</var><sup>2</sup> + 2<var>b</var><sup>2</sup> + 2<var>ab</var>)(<var>a</var><sup>2</sup> + 2<var>b</var><sup>2</sup> &minus; 2<var>ab</var>). Узнали форму &mdash; дополняйте до неё.',
   'en': 'An integer equation with a product of variables, or a huge number of the form <var>a</var><sup>4</sup> + 4<var>b</var><sup>4</sup>, signals that factoring &mdash; not computing &mdash; solves the problem. Two workhorses: Simon&rsquo;s Favorite Factoring Trick (add a constant so that <var>xy</var> + <var>ax</var> + <var>by</var> folds into a product of two binomials) and the Sophie Germain identity: <var>a</var><sup>4</sup> + 4<var>b</var><sup>4</sup> = (<var>a</var><sup>2</sup> + 2<var>b</var><sup>2</sup> + 2<var>ab</var>)(<var>a</var><sup>2</sup> + 2<var>b</var><sup>2</sup> &minus; 2<var>ab</var>). Recognize the shape, then complete it.'},
  'probs': [
   {'tag': {'ru': 'Задача 1 · приём Симона', 'en': 'Problem 1 · Simon&rsquo;s trick'},
    'q': {'ru': 'Сколько пар натуральных чисел (<var>x</var>;&nbsp;<var>y</var>) удовлетворяет уравнению <var>xy</var> + 3<var>x</var> + 2<var>y</var> = 42?',
          'en': 'How many ordered pairs of positive integers (<var>x</var>,&nbsp;<var>y</var>) satisfy <var>xy</var> + 3<var>x</var> + 2<var>y</var> = 42?'},
    'sol': {'ru': 'Тупик: выразить <var>y</var> = (42 &minus; 3<var>x</var>)/(<var>x</var> + 2) и перебирать <var>x</var> по одному, каждый раз проверяя делимость. Работает, но медленно и без гарантии, что ничего не упущено. Приём Симона: сгруппируем <var>x</var>(<var>y</var> + 3) + 2<var>y</var> и добавим 6, чтобы замкнуть вторую скобку: <var>xy</var> + 3<var>x</var> + 2<var>y</var> + 6 = (<var>x</var> + 2)(<var>y</var> + 3) = 48. Теперь это задача о делителях. Так как <var>x</var> &ge; 1 и <var>y</var> &ge; 1, нужны делители 48 с условиями <var>x</var> + 2 &ge; 3 и <var>y</var> + 3 &ge; 4, то есть 3 &le; <var>x</var> + 2 &le; 12. Делители 48: 1, 2, 3, 4, 6, 8, 12, 16, 24, 48; подходят 3, 4, 6, 8, 12. Это пары (1;&nbsp;13), (2;&nbsp;9), (4;&nbsp;5), (6;&nbsp;3), (10;&nbsp;1) &mdash; всего <b>5</b>. Проверка одной: 4&middot;5 + 12 + 10 = 42. Верно.',
           'en': 'The dead end: solve for <var>y</var> = (42 &minus; 3<var>x</var>)/(<var>x</var> + 2) and test <var>x</var> one by one, checking divisibility each time. It works, but slowly and with no guarantee of completeness. Simon&rsquo;s trick: group <var>x</var>(<var>y</var> + 3) + 2<var>y</var> and add 6 to close the second binomial: <var>xy</var> + 3<var>x</var> + 2<var>y</var> + 6 = (<var>x</var> + 2)(<var>y</var> + 3) = 48. Now it is a divisor problem. Since <var>x</var> &ge; 1 and <var>y</var> &ge; 1, we need divisors of 48 with <var>x</var> + 2 &ge; 3 and <var>y</var> + 3 &ge; 4, that is 3 &le; <var>x</var> + 2 &le; 12. Divisors of 48: 1, 2, 3, 4, 6, 8, 12, 16, 24, 48; those that qualify: 3, 4, 6, 8, 12. They give (1,&nbsp;13), (2,&nbsp;9), (4,&nbsp;5), (6,&nbsp;3), (10,&nbsp;1) &mdash; <b>5</b> pairs in all. Check one: 4&middot;5 + 12 + 10 = 42. Correct.'}},
   {'tag': {'ru': 'Задача 2 · Софи Жермен', 'en': 'Problem 2 · Sophie Germain'},
    'q': {'ru': 'Найдите наибольший простой делитель числа 20<sup>4</sup> + 4&nbsp;&middot;&nbsp;9<sup>4</sup>.',
          'en': 'Find the largest prime factor of 20<sup>4</sup> + 4&nbsp;&middot;&nbsp;9<sup>4</sup>.'},
    'sol': {'ru': 'Тупик: вычислить 160&nbsp;000 + 26&nbsp;244 = 186&nbsp;244 и делить подряд на простые &mdash; до нужного делителя добираться пришлось бы за сотню проб. Приём: форма <var>a</var><sup>4</sup> + 4<var>b</var><sup>4</sup> &mdash; это тождество Софи Жермен с <var>a</var> = 20, <var>b</var> = 9 (само тождество &mdash; двойная разность квадратов: <var>a</var><sup>4</sup> + 4<var>b</var><sup>4</sup> = (<var>a</var><sup>2</sup> + 2<var>b</var><sup>2</sup>)<sup>2</sup> &minus; (2<var>ab</var>)<sup>2</sup>). Считаем скобки: <var>a</var><sup>2</sup> + 2<var>b</var><sup>2</sup> = 400 + 162 = 562, 2<var>ab</var> = 360. Значит, число равно (562 + 360)(562 &minus; 360) = 922&nbsp;&middot;&nbsp;202. Дораскладываем: 922 = 2&nbsp;&middot;&nbsp;461, 202 = 2&nbsp;&middot;&nbsp;101. Число 461 не делится на 2, 3, 5, 7, 11, 13, 17, 19 (а 21<sup>2</sup> &gt; 461), значит простое; 101 тоже простое. Итого 186&nbsp;244 = 2<sup>2</sup>&nbsp;&middot;&nbsp;101&nbsp;&middot;&nbsp;461, и наибольший простой делитель &mdash; <b>461</b>.',
           'en': 'The dead end: compute 160,000 + 26,244 = 186,244 and trial-divide by primes &mdash; you would need on the order of a hundred trials to reach the right one. The trick: the shape <var>a</var><sup>4</sup> + 4<var>b</var><sup>4</sup> is the Sophie Germain identity with <var>a</var> = 20, <var>b</var> = 9 (the identity itself is a disguised difference of squares: <var>a</var><sup>4</sup> + 4<var>b</var><sup>4</sup> = (<var>a</var><sup>2</sup> + 2<var>b</var><sup>2</sup>)<sup>2</sup> &minus; (2<var>ab</var>)<sup>2</sup>). Evaluate the pieces: <var>a</var><sup>2</sup> + 2<var>b</var><sup>2</sup> = 400 + 162 = 562, 2<var>ab</var> = 360. So the number equals (562 + 360)(562 &minus; 360) = 922&nbsp;&middot;&nbsp;202. Factor further: 922 = 2&nbsp;&middot;&nbsp;461, 202 = 2&nbsp;&middot;&nbsp;101. The number 461 is divisible by none of 2, 3, 5, 7, 11, 13, 17, 19 (and 21<sup>2</sup> &gt; 461), so it is prime; 101 is prime too. Altogether 186,244 = 2<sup>2</sup>&nbsp;&middot;&nbsp;101&nbsp;&middot;&nbsp;461, and the largest prime factor is <b>461</b>.'}},
  ]},

 # ── И4 / T4 ──────────────────────────────────────────────────────────
 {'id': 'И4', 'id_en': 'T4', 'anchor': 'tk4', 'minutes': 15,
  'title': {'ru': 'Виета глубже',
            'en': 'Vieta Beyond the Basics'},
  'intro': {
   'ru': 'Формулы Виета &mdash; это не только &laquo;сумма и произведение корней&raquo;. Из <var>r</var> + <var>s</var> и <var>rs</var> собирается любая симметричная комбинация (квадраты, кубы, обратные), строится новое квадратное уравнение со сдвинутыми или обратными корнями, а требование &laquo;корни целые&raquo; превращается в задачу о делителях. Сигналы: просят не корни, а выражение от них; в уравнении параметр, и спрашивают, при каких его значениях корни целые.',
   'en': 'Vieta&rsquo;s formulas are more than &ldquo;sum and product of the roots.&rdquo; From <var>r</var> + <var>s</var> and <var>rs</var> you can assemble any symmetric combination (squares, cubes, reciprocals), build a new quadratic whose roots are shifted or reciprocal, and turn the demand &ldquo;the roots are integers&rdquo; into a divisor problem. Signals: the question asks for an expression in the roots rather than the roots; the equation has a parameter and asks for which values the roots are integers.'},
  'probs': [
   {'tag': {'ru': 'Задача 1 · новое уравнение из старого', 'en': 'Problem 1 · a new quadratic from an old one'},
    'q': {'ru': 'Пусть <var>r</var> и <var>s</var> &mdash; корни уравнения <var>x</var><sup>2</sup> &minus; 6<var>x</var> + 2 = 0. Квадратное уравнение <var>x</var><sup>2</sup> + <var>b</var><var>x</var> + <var>c</var> = 0 имеет корни <var>r</var><sup>2</sup> и <var>s</var><sup>2</sup>. Чему равно <var>b</var> + <var>c</var>?',
          'en': 'Let <var>r</var> and <var>s</var> be the roots of <var>x</var><sup>2</sup> &minus; 6<var>x</var> + 2 = 0. The quadratic <var>x</var><sup>2</sup> + <var>b</var><var>x</var> + <var>c</var> = 0 has roots <var>r</var><sup>2</sup> and <var>s</var><sup>2</sup>. What is <var>b</var> + <var>c</var>?'},
    'sol': {'ru': 'Тупик: найти корни явно, <var>r</var>, <var>s</var> = 3 &plusmn; &radic;7, возвести в квадрат и собирать уравнение из иррациональностей. Приём: новое уравнение строится из суммы и произведения новых корней, а те выражаются через старые по Виета. Старые: <var>r</var> + <var>s</var> = 6, <var>rs</var> = 2. Сумма новых: <var>r</var><sup>2</sup> + <var>s</var><sup>2</sup> = (<var>r</var> + <var>s</var>)<sup>2</sup> &minus; 2<var>rs</var> = 36 &minus; 4 = 32. Произведение новых: <var>r</var><sup>2</sup><var>s</var><sup>2</sup> = (<var>rs</var>)<sup>2</sup> = 4. По Виета для нового уравнения <var>b</var> = &minus;32 (минус сумма!), <var>c</var> = 4. Знак &mdash; главная ловушка: половина неверных ответов здесь &mdash; это +32. Итог: <var>b</var> + <var>c</var> = &minus;32 + 4 = <b>&minus;28</b>.',
           'en': 'The dead end: find the roots explicitly, <var>r</var>, <var>s</var> = 3 &plusmn; &radic;7, square them and assemble the equation out of irrationalities. The trick: the new quadratic is built from the sum and product of the new roots, and those come from the old ones via Vieta. Old: <var>r</var> + <var>s</var> = 6, <var>rs</var> = 2. New sum: <var>r</var><sup>2</sup> + <var>s</var><sup>2</sup> = (<var>r</var> + <var>s</var>)<sup>2</sup> &minus; 2<var>rs</var> = 36 &minus; 4 = 32. New product: <var>r</var><sup>2</sup><var>s</var><sup>2</sup> = (<var>rs</var>)<sup>2</sup> = 4. By Vieta for the new equation, <var>b</var> = &minus;32 (MINUS the sum!) and <var>c</var> = 4. The sign is the trap: half of all wrong answers here are +32. So <var>b</var> + <var>c</var> = &minus;32 + 4 = <b>&minus;28</b>.'}},
   {'tag': {'ru': 'Задача 2 · целые корни и делители', 'en': 'Problem 2 · integer roots and divisors'},
    'q': {'ru': 'Для скольких целых значений <var>k</var> уравнение <var>x</var><sup>2</sup> &minus; <var>kx</var> + 36 = 0 имеет два целых корня (не обязательно различных)?',
          'en': 'For how many integer values of <var>k</var> does the equation <var>x</var><sup>2</sup> &minus; <var>kx</var> + 36 = 0 have two integer roots (not necessarily distinct)?'},
    'sol': {'ru': 'Тупик: требовать, чтобы дискриминант <var>k</var><sup>2</sup> &minus; 144 был точным квадратом, и перебирать <var>k</var> &mdash; условие верное, но перебор длинный и легко потерять отрицательные значения. Приём: по Виета целые корни <var>r</var>, <var>s</var> дают <var>rs</var> = 36 и <var>k</var> = <var>r</var> + <var>s</var>, так что <var>k</var> &mdash; это сумма пары делителей числа 36 одного знака. Положительные пары: (1;&nbsp;36), (2;&nbsp;18), (3;&nbsp;12), (4;&nbsp;9), (6;&nbsp;6) &mdash; суммы 37, 20, 15, 13, 12: пять значений. Оба корня могут быть и отрицательными (произведение всё равно 36!) &mdash; это даёт ещё пять: &minus;37, &minus;20, &minus;15, &minus;13, &minus;12. Все десять сумм различны, значит, значений <var>k</var> ровно <b>10</b>. Контроль через дискриминант: <var>k</var> = 13 даёт 169 &minus; 144 = 25 = 5<sup>2</sup>. Сходится.',
           'en': 'The dead end: demand that the discriminant <var>k</var><sup>2</sup> &minus; 144 be a perfect square and scan values of <var>k</var> &mdash; a correct condition, but the scan is long and the negative values are easy to lose. The trick: by Vieta, integer roots <var>r</var>, <var>s</var> give <var>rs</var> = 36 and <var>k</var> = <var>r</var> + <var>s</var>, so <var>k</var> is the sum of a same-sign divisor pair of 36. Positive pairs: (1,&nbsp;36), (2,&nbsp;18), (3,&nbsp;12), (4,&nbsp;9), (6,&nbsp;6) &mdash; sums 37, 20, 15, 13, 12: five values. Both roots may also be negative (the product is still 36!), giving five more: &minus;37, &minus;20, &minus;15, &minus;13, &minus;12. All ten sums are distinct, so there are exactly <b>10</b> values of <var>k</var>. Discriminant check: <var>k</var> = 13 gives 169 &minus; 144 = 25 = 5<sup>2</sup>. It fits.'}},
  ]},

 # ── И5 / T5 ──────────────────────────────────────────────────────────
 {'id': 'И5', 'id_en': 'T5', 'anchor': 'tk5', 'minutes': 15,
  'title': {'ru': 'Оценка и сравнение без вычисления',
            'en': 'Estimation and Comparison Without Computing'},
  'intro': {
   'ru': 'Когда числа заведомо не вычислить &mdash; степени с показателем 40, суммы ста корней, &mdash; задача просит не значение, а сравнение или две соседние границы. Инструменты: привести степени к общему показателю (сравнивать основания) или общему основанию (сравнивать показатели); зажать сумму между двумя интегральными &laquo;лесенками&raquo; из разностей корней. Сигналы: &laquo;что больше&raquo;, &laquo;между какими целыми&raquo;, &laquo;чему равна целая часть&raquo;.',
   'en': 'When the numbers are plainly uncomputable &mdash; powers with exponent 40, sums of a hundred radicals &mdash; the problem is asking not for a value but for a comparison or two neighboring bounds. Tools: bring powers to a common exponent (compare bases) or a common base (compare exponents); squeeze a sum between two &ldquo;staircases&rdquo; built from differences of radicals. Signals: &ldquo;which is larger,&rdquo; &ldquo;between which integers,&rdquo; &ldquo;what is the integer part.&rdquo;'},
  'probs': [
   {'tag': {'ru': 'Задача 1 · общий показатель', 'en': 'Problem 1 · common exponent'},
    'q': {'ru': 'Расположите числа <var>A</var> = 2<sup>60</sup>, <var>B</var> = 3<sup>40</sup>, <var>C</var> = 10<sup>18</sup> в порядке возрастания.',
          'en': 'Arrange the numbers <var>A</var> = 2<sup>60</sup>, <var>B</var> = 3<sup>40</sup>, <var>C</var> = 10<sup>18</sup> in increasing order.'},
    'sol': {'ru': 'Тупик: прикидывать количество цифр через логарифмы, которых на AMC нет под рукой, или, хуже, пытаться перемножать. Приём: у 60 и 40 общий делитель 20 &mdash; приводим к общему показателю: <var>A</var> = (2<sup>3</sup>)<sup>20</sup> = 8<sup>20</sup>, <var>B</var> = (3<sup>2</sup>)<sup>20</sup> = 9<sup>20</sup>. Основание 9 больше основания 8, значит <var>B</var> &gt; <var>A</var>. Теперь <var>C</var>: показатель 18 к двадцатке не приводится, зато 2<sup>60</sup> = (2<sup>10</sup>)<sup>6</sup> = 1024<sup>6</sup>, а 10<sup>18</sup> = (10<sup>3</sup>)<sup>6</sup> = 1000<sup>6</sup>. Так как 1024 &gt; 1000, получаем <var>A</var> &gt; <var>C</var>. Итог: <b><var>C</var> &lt; <var>A</var> &lt; <var>B</var></b>, то есть 10<sup>18</sup> &lt; 2<sup>60</sup> &lt; 3<sup>40</sup>. Весь ход &mdash; два переписывания степеней, ни одного большого числа.',
           'en': 'The dead end: estimate digit counts via logarithms you do not have at the AMC, or worse, try to multiply things out. The trick: 60 and 40 share the divisor 20 &mdash; bring both to a common exponent: <var>A</var> = (2<sup>3</sup>)<sup>20</sup> = 8<sup>20</sup>, <var>B</var> = (3<sup>2</sup>)<sup>20</sup> = 9<sup>20</sup>. Base 9 beats base 8, so <var>B</var> &gt; <var>A</var>. Now <var>C</var>: the exponent 18 does not match 20, but 2<sup>60</sup> = (2<sup>10</sup>)<sup>6</sup> = 1024<sup>6</sup> while 10<sup>18</sup> = (10<sup>3</sup>)<sup>6</sup> = 1000<sup>6</sup>. Since 1024 &gt; 1000, we get <var>A</var> &gt; <var>C</var>. Conclusion: <b><var>C</var> &lt; <var>A</var> &lt; <var>B</var></b>, that is 10<sup>18</sup> &lt; 2<sup>60</sup> &lt; 3<sup>40</sup>. The whole solution is two rewritings of powers &mdash; not a single large number computed.'}},
   {'tag': {'ru': 'Задача 2 · зажать сумму корней', 'en': 'Problem 2 · squeezing a sum of radicals'},
    'q': {'ru': f'Чему равна целая часть суммы <var>S</var> = {F("1","&radic;1")} + {F("1","&radic;2")} + {F("1","&radic;3")} + &hellip; + {F("1","&radic;100")}?',
          'en': f'What is the integer part of the sum <var>S</var> = {F("1","&radic;1")} + {F("1","&radic;2")} + {F("1","&radic;3")} + &hellip; + {F("1","&radic;100")}?'},
    'sol': {'ru': f'Тупик: складывать сто иррациональных слагаемых с точностью до сотых &mdash; за отведённые три минуты нереально. Приём: зажмём каждое слагаемое разностью корней. Домножив на сопряжённое, получаем 2(&radic;(<var>k</var>+1) &minus; &radic;<var>k</var>) = {F("2","&radic;(<var>k</var>+1) + &radic;<var>k</var>")} &lt; {F("1","&radic;<var>k</var>")} &lt; {F("2","&radic;<var>k</var> + &radic;(<var>k</var>&minus;1)")} = 2(&radic;<var>k</var> &minus; &radic;(<var>k</var>&minus;1)). Обе стороны телескопируются! Нижняя оценка: <var>S</var> &gt; 2(&radic;101 &minus; &radic;1) &gt; 2(10,05 &minus; 1) = 18,1. Верхняя (первый член берём как есть, единицу, остальные оцениваем): <var>S</var> &lt; 1 + 2(&radic;100 &minus; &radic;1) = 1 + 18 = 19. Итак, 18,1 &lt; <var>S</var> &lt; 19, и целая часть равна <b>18</b>. Реальное значение <var>S</var> &asymp; 18,59 &mdash; оценка честно его окружила.',
           'en': f'The dead end: add a hundred irrational terms to two decimal places &mdash; impossible in the three minutes you have. The trick: squeeze each term between differences of radicals. Multiplying by the conjugate gives 2(&radic;(<var>k</var>+1) &minus; &radic;<var>k</var>) = {F("2","&radic;(<var>k</var>+1) + &radic;<var>k</var>")} &lt; {F("1","&radic;<var>k</var>")} &lt; {F("2","&radic;<var>k</var> + &radic;(<var>k</var>&minus;1)")} = 2(&radic;<var>k</var> &minus; &radic;(<var>k</var>&minus;1)). Both sides telescope! Lower bound: <var>S</var> &gt; 2(&radic;101 &minus; &radic;1) &gt; 2(10.05 &minus; 1) = 18.1. Upper bound (keep the first term, 1, as is and bound the rest): <var>S</var> &lt; 1 + 2(&radic;100 &minus; &radic;1) = 1 + 18 = 19. So 18.1 &lt; <var>S</var> &lt; 19, and the integer part is <b>18</b>. The true value is <var>S</var> &asymp; 18.59 &mdash; safely inside the trap we built.'}},
  ]},

 # ── И6 / T6 ──────────────────────────────────────────────────────────
 {'id': 'И6', 'id_en': 'T6', 'anchor': 'tk6', 'minutes': 15,
  'title': {'ru': 'Уравнения с ограничениями',
            'en': 'Equations with Built-in Constraints'},
  'intro': {
   'ru': 'Иногда главный инструмент &mdash; не преобразование, а само ограничение: число решений уравнения с модулем скачет в зависимости от параметра; линейная связь превращает выражение от двух переменных в квадратный трёхчлен от одной. Сигналы: &laquo;при каких значениях параметра ровно <var>N</var> решений&raquo;, &laquo;наибольшее значение <var>xy</var> при условии&hellip;&raquo;. План один: подставить ограничение, свести к одной переменной, разобрать пограничные случаи.',
   'en': 'Sometimes the main tool is not a transformation but the constraint itself: the number of solutions of an absolute-value equation jumps as a parameter moves; a linear relation turns a two-variable expression into a one-variable quadratic. Signals: &ldquo;for which parameter values are there exactly <var>N</var> solutions,&rdquo; &ldquo;the greatest value of <var>xy</var> given that&hellip;&rdquo; The plan is always the same: substitute the constraint, reduce to one variable, examine the borderline cases.'},
  'probs': [
   {'tag': {'ru': 'Задача 1 · модуль с параметром', 'en': 'Problem 1 · absolute value with a parameter'},
    'q': {'ru': 'При каком значении параметра <var>a</var> уравнение ||<var>x</var> &minus; 4| &minus; 3| = <var>a</var> имеет ровно три корня?',
          'en': 'For what value of the parameter <var>a</var> does the equation ||<var>x</var> &minus; 4| &minus; 3| = <var>a</var> have exactly three solutions?'},
    'sol': {'ru': 'Тупик: раскрывать четыре комбинации знаков и решать каждую при произвольном <var>a</var> &mdash; каша из случаев без картины целого. Приём: считаем корни послойно, следя, когда ветка вырождается. При <var>a</var> &lt; 0 корней нет. При <var>a</var> &ge; 0 первый слой даёт |<var>x</var> &minus; 4| = 3 + <var>a</var> или |<var>x</var> &minus; 4| = 3 &minus; <var>a</var>. Первая ветка: 3 + <var>a</var> &gt; 0 всегда &mdash; ровно 2 корня. Вторая ветка: 2 корня при 3 &minus; <var>a</var> &gt; 0, ОДИН корень (<var>x</var> = 4) при 3 &minus; <var>a</var> = 0 и ноль при <var>a</var> &gt; 3. Итого: 4 корня при 0 &le; <var>a</var> &lt; 3, три &mdash; только когда вторая ветка вырождается в точку: <var>a</var> = <b>3</b>. Проверка: ||<var>x</var> &minus; 4| &minus; 3| = 3 даёт |<var>x</var> &minus; 4| = 6 (корни &minus;2 и 10) или |<var>x</var> &minus; 4| = 0 (корень 4) &mdash; ровно три. Нечётное число корней у симметричного уравнения &mdash; всегда знак вырожденной ветки в центре симметрии.',
           'en': 'The dead end: expand four sign combinations and solve each for arbitrary <var>a</var> &mdash; a porridge of cases with no view of the whole. The trick: count solutions layer by layer, watching for the branch that degenerates. For <var>a</var> &lt; 0 there are no solutions. For <var>a</var> &ge; 0 the outer layer gives |<var>x</var> &minus; 4| = 3 + <var>a</var> or |<var>x</var> &minus; 4| = 3 &minus; <var>a</var>. First branch: 3 + <var>a</var> &gt; 0 always &mdash; exactly 2 solutions. Second branch: 2 solutions while 3 &minus; <var>a</var> &gt; 0, ONE solution (<var>x</var> = 4) when 3 &minus; <var>a</var> = 0, none for <var>a</var> &gt; 3. Tally: 4 solutions for 0 &le; <var>a</var> &lt; 3; three occur only when the second branch collapses to a point: <var>a</var> = <b>3</b>. Check: ||<var>x</var> &minus; 4| &minus; 3| = 3 gives |<var>x</var> &minus; 4| = 6 (roots &minus;2 and 10) or |<var>x</var> &minus; 4| = 0 (root 4) &mdash; exactly three. An odd solution count for a symmetric equation always signals a degenerate branch at the center of symmetry.'}},
   {'tag': {'ru': 'Задача 2 · максимум при линейной связи', 'en': 'Problem 2 · maximum under a linear constraint'},
    'q': {'ru': 'Действительные числа <var>x</var> и <var>y</var> удовлетворяют условию 2<var>x</var> + 3<var>y</var> = 12. Каково наибольшее значение произведения <var>xy</var>?',
          'en': 'Real numbers <var>x</var> and <var>y</var> satisfy 2<var>x</var> + 3<var>y</var> = 12. What is the greatest value of the product <var>xy</var>?'},
    'sol': {'ru': f'Тупик: перебирать &laquo;красивые&raquo; пары вроде (3;&nbsp;2) или (6;&nbsp;0) и надеяться, что максимум среди них &mdash; перебор ничего не доказывает. Приём: подставим ограничение и сведём к одной переменной. Из связи <var>x</var> = (12 &minus; 3<var>y</var>)/2, значит <var>xy</var> = {F("(12 &minus; 3<var>y</var>)<var>y</var>","2")} = {F("12<var>y</var> &minus; 3<var>y</var><sup>2</sup>","2")} &mdash; парабола ветвями вниз, максимум в вершине. Вершина: <var>y</var> = 12/(2&nbsp;&middot;&nbsp;3) = 2, тогда <var>x</var> = 3 и <var>xy</var> = <b>6</b>. Никакого анализа &mdash; только вершина параболы. Красивая перекрёстная проверка: в точке максимума 2<var>x</var> = 3<var>y</var> = 6, то есть линейный &laquo;бюджет&raquo; делится между слагаемыми поровну &mdash; общий факт, который стоит запомнить как мгновенный контроль ответа.',
           'en': f'The dead end: try &ldquo;nice&rdquo; pairs like (3,&nbsp;2) or (6,&nbsp;0) and hope the maximum is among them &mdash; a search proves nothing. The trick: substitute the constraint and reduce to one variable. From the relation, <var>x</var> = (12 &minus; 3<var>y</var>)/2, so <var>xy</var> = {F("(12 &minus; 3<var>y</var>)<var>y</var>","2")} = {F("12<var>y</var> &minus; 3<var>y</var><sup>2</sup>","2")} &mdash; a downward parabola, maximized at its vertex. Vertex: <var>y</var> = 12/(2&nbsp;&middot;&nbsp;3) = 2, whence <var>x</var> = 3 and <var>xy</var> = <b>6</b>. No calculus &mdash; just the vertex of a parabola. A pleasing cross-check: at the maximum, 2<var>x</var> = 3<var>y</var> = 6 &mdash; the linear &ldquo;budget&rdquo; splits evenly between the two terms, a general fact worth remembering as an instant answer check.'}},
  ]},
 ]
}
