# -*- coding: utf-8 -*-
"""Пробный тест AMC 8: 25 оригинальных задач, RU+EN. v2 после раунда рецензий."""

def F(a, b):
    return f'<span class="frac"><span>{a}</span><span>{b}</span></span>'

P = [
 ('У Маши 3 пакета по 12 наклеек и ещё 7 наклеек россыпью. Сколько наклеек у Маши всего?',
  'Maya has 3 packs of 12 stickers each and 7 loose stickers. How many stickers does Maya have in all?',
  ['36', '40', '43', '46', '55'], None),
 ('Какая из дробей самая большая?',
  'Which of the following fractions is the largest?',
  ['<span class="frac"><span>2</span><span>5</span></span>', '<span class="frac"><span>3</span><span>7</span></span>', '<span class="frac"><span>4</span><span>9</span></span>', '<span class="frac"><span>1</span><span>2</span></span>', '<span class="frac"><span>5</span><span>9</span></span>'], None),
 ('Периметр прямоугольника со сторонами 3 и 7 равен',
  'The perimeter of a rectangle with side lengths 3 and 7 is',
  ['10', '20', '21', '24', '42'], None),
 ('100 конфет раскладывают в пакетики по 7 конфет. Сколько конфет останется?',
  '100 candies are packed into bags of 7 candies each. How many candies are left over?',
  ['1', '2', '3', '4', '5'], None),
 ('Чему равно 25 % от 84?',
  'What is 25% of 84?',
  ['19', '20', '21', '25', '28'], None),
 ('Фильм начался в 14:45 и идёт 1 час 50 минут. Когда он закончится?',
  'A movie starts at 2:45 pm and runs for 1 hour 50 minutes. When does it end?',
  ['16:25', '16:30', '16:35', '16:45', '16:55'], ['4:25 pm', '4:30 pm', '4:35 pm', '4:45 pm', '4:55 pm']),
 ('Велосипедист проехал 3 км за 30 минут. Какова его скорость в километрах в час?',
  'A cyclist rode 3 miles in 30 minutes. What was the cyclist&rsquo;s speed in miles per hour?',
  ['1,5', '3', '4,5', '6', '9'], ['1.5', '3', '4.5', '6', '9']),
 ('Число 40 разделили на две части в отношении 2 : 3. Чему равна большая часть?',
  'The number 40 is split into two parts in the ratio 2 : 3. What is the larger part?',
  ['16', '18', '20', '24', '28'], None),
 ('В последовательности 7, 11, 15, 19, &hellip; каждый член на 4 больше предыдущего. Чему равен десятый член?',
  'In the sequence 7, 11, 15, 19, &hellip; each term is 4 more than the previous one. What is the tenth term?',
  ['43', '45', '47', '49', '51'], None),
 ('На игральном кубике сумма очков на всех шести гранях равна 21. Кубик стоит на столе; наблюдатель видит три его грани, и на них 1, 2 и 3. Чему равна сумма очков на трёх невидимых гранях?',
  'The numbers on all six faces of a die add up to 21. The die sits on a table; an observer sees three of its faces, showing 1, 2, and 3. What is the sum of the numbers on the three hidden faces?',
  ['12', '13', '14', '15', '16'], None),
 ('Цена игрушки 90 долларов. На распродаже её уценили на 30 %. Сколько теперь стоит игрушка (в долларах)?',
  'A toy costs $90. During a sale, its price is reduced by 30%. What does the toy cost now (in dollars)?',
  ['27', '57', '60', '63', '70'], None),
 ('Из квадрата со стороной 6 вырезали (из угла) квадрат со стороной 2. Чему равна площадь оставшейся фигуры?',
  'A square of side 2 is cut from the corner of a square of side 6. What is the area of the remaining figure?',
  ['24', '26', '28', '30', '32'], None),
 ('Сколько существует двузначных чисел, сумма цифр которых равна 9?',
  'How many two-digit numbers have digit sum 9?',
  ['8', '9', '10', '11', '12'], None),
 ('От остановки автобус №1 отходит каждые 12 минут, автобус №2 &mdash; каждые 18 минут. В полдень они отошли вместе. Через сколько минут они снова отойдут одновременно?',
  'Bus 1 leaves a stop every 12 minutes, and bus 2 every 18. They leave together at noon. In how many minutes will they next leave together?',
  ['24', '30', '36', '54', '72'], None),
 ('В мешке 3 красных и 5 синих шариков. Наугад достают один шарик. Какова вероятность, что он красный?',
  'A bag holds 3 red and 5 blue marbles. One marble is drawn at random. What is the probability that it is red?',
  ['<span class="frac"><span>1</span><span>8</span></span>', '<span class="frac"><span>1</span><span>4</span></span>', '<span class="frac"><span>1</span><span>3</span></span>', '<span class="frac"><span>3</span><span>8</span></span>', '<span class="frac"><span>1</span><span>2</span></span>'], None),
 ('На вечеринке было 8 человек, и каждый пожал руку каждому ровно один раз. Сколько было рукопожатий?',
  'At a party, each of 8 people shook hands with every other person exactly once. How many handshakes were there?',
  ['16', '28', '36', '56', '64'], None),
 ('Отцу 38 лет, сыну 8. Через сколько лет отец будет ровно вдвое старше сына?',
  'A father is 38 and his son is 8. In how many years will the father be exactly twice as old as his son?',
  ['11', '15', '18', '22', '30'], None),
 ('Треть учеников класса ушла на экскурсию, затем четверть оставшихся ушла на репетицию. В классе осталось 18 учеников. Сколько учеников в классе всего?',
  'A third of a class left for a field trip, then a quarter of those remaining left for a rehearsal. Eighteen students stayed in the room. How many students are in the class?',
  ['24', '27', '32', '36', '48'], None),
 ('Сколько раз цифра 7 встречается в записи чисел от 1 до 100?',
  'How many times does the digit 7 appear when the numbers from 1 to 100 are written out?',
  ['10', '16', '18', '19', '20'], None),
 ('Сколько существует трёхзначных чисел, у которых все три цифры различны и нечётны?',
  'How many three-digit numbers have three different digits, all of them odd?',
  ['45', '48', '60', '75', '100'], None),
 ('Каково наименьшее натуральное число, большее 1, которое при делении на 2, на 3, на 4 и на 5 даёт остаток 1?',
  'What is the least positive integer greater than 1 that leaves a remainder of 1 when divided by each of 2, 3, 4, and 5?',
  ['21', '31', '41', '61', '121'], None),
 ('Двузначное число увеличивается ровно на 75 %, если переставить его цифры местами. Сколько существует таких двузначных чисел?',
  'A two-digit number increases by exactly 75% when its digits are reversed. How many such two-digit numbers are there?',
  ['3', '4', '5', '6', '8'], None),
 ('Периметр прямоугольника равен 26, а площадь равна 40. На сколько длинная сторона больше короткой?',
  'A rectangle has perimeter 26 and area 40. By how much is the longer side greater than the shorter side?',
  ['2', '3', '5', '8', '13'], None),
 ('У Ани 15 монет — по 5 и по 25 центов, всего на 2 доллара 15 центов. Сколько у неё монет по 25 центов?',
  'Anya has 15 coins, nickels and quarters, worth $2.15 in all. How many quarters does she have?',
  ['5', '6', '7', '8', '9'], None),
 ('Сколькими нулями оканчивается произведение 1&middot;2&middot;3&middot;&hellip;&middot;25?',
  'In how many zeros does the product 1&middot;2&middot;3&middot;&hellip;&middot;25 end?',
  ['5', '6', '7', '8', '10'], None),
]

KEY = ['C', 'E', 'B', 'B', 'C', 'C', 'D', 'D', 'A', 'D', 'D', 'E', 'B', 'C', 'D', 'B', 'D', 'D', 'E', 'C', 'D', 'B', 'B', 'C', 'B']

HINTS = {
 'ru': [
  '3&middot;12 + 7 = 43.',
  'Сравните с половиной: только 1/2 и 5/9 не меньше половины, а 5/9 &gt; 1/2 (5&middot;2 &gt; 9).',
  '2(3 + 7) = 20.',
  '100 = 14&middot;7 + 2: остаток 2.',
  'Четверть от 84: 84/4 = 21.',
  '1 час 50 минут после 14:45: 16:35.',
  '3 км за полчаса &mdash; это 6 км за час.',
  'Часть = 40/5 = 8: части 16 и 24, большая 24.',
  '7 + 9&middot;4 = 43 (девять шагов по 4).',
  '21 &minus; (1 + 2 + 3) = 15.',
  '30 % от 90 = 27, значит 90 &minus; 27 = 63.',
  '36 &minus; 4 = 32.',
  'Первая цифра от 1 до 9, вторая определяется: 18, 27, &hellip;, 90 &mdash; девять чисел.',
  'НОК(12, 18) = 36.',
  '3 красных из 8 шариков: 3/8.',
  'Каждая пара из 8 человек: 8&middot;7/2 = 28.',
  '38 + <var>x</var> = 2(8 + <var>x</var>): <var>x</var> = 22.',
  'Осталось (2/3)&middot;(3/4) = 1/2 класса, значит всего 36.',
  'Десять раз в единицах (7, 17, &hellip;, 97) и десять в десятках (70&ndash;79): всего 20.',
  'Нечётных цифр пять (1, 3, 5, 7, 9): 5&middot;4&middot;3 = 60.',
  'Число на 1 больше кратного НОК(2,3,4,5) = 60: это 61.',
  'Если число 10<var>a</var>+<var>b</var>, то 10<var>b</var>+<var>a</var> = 1,75(10<var>a</var>+<var>b</var>), откуда <var>b</var> = 2<var>a</var>: числа 12, 24, 36, 48 — четыре.',
  'Сумма сторон 13, произведение 40: стороны 5 и 8, разность 3.',
  'Если четвертаков <var>q</var>, то 25<var>q</var> + 5(15 &minus; <var>q</var>) = 215: <var>q</var> = 7.',
  'Каждый ноль — это пара 2&times;5; пятёрок меньше: их дают 5, 10, 15, 20 и 25 (две), итого 6.',
 ],
 'en': [
  '3&middot;12 + 7 = 43.',
  'Compare with one half: only 1/2 and 5/9 are at least a half, and 5/9 &gt; 1/2 (since 5&middot;2 &gt; 9).',
  '2(3 + 7) = 20.',
  '100 = 14&middot;7 + 2: remainder 2.',
  'A quarter of 84: 84/4 = 21.',
  '1 hour 50 minutes after 2:45 pm is 4:35 pm.',
  '3 miles in half an hour is 6 miles per hour.',
  'One part = 40/5 = 8: the parts are 16 and 24; the larger is 24.',
  '7 + 9&middot;4 = 43 (nine steps of 4).',
  '21 &minus; (1 + 2 + 3) = 15.',
  '30% of 90 = 27, so 90 &minus; 27 = 63.',
  '36 &minus; 4 = 32.',
  'The tens digit runs 1 through 9 and determines the units digit: 18, 27, &hellip;, 90 &mdash; nine numbers.',
  'LCM(12, 18) = 36.',
  '3 red out of 8 marbles: 3/8.',
  'Every pair of 8 people: 8&middot;7/2 = 28.',
  '38 + <var>x</var> = 2(8 + <var>x</var>): <var>x</var> = 22.',
  '(2/3)&middot;(3/4) = 1/2 of the class stayed, so the class has 36 students.',
  'Ten times in the units place (7, 17, &hellip;, 97) and ten in the tens place (70&ndash;79): 20 in all.',
  'There are five odd digits (1, 3, 5, 7, 9): 5&middot;4&middot;3 = 60.',
  'One more than a multiple of LCM(2,3,4,5) = 60: that is 61.',
  'If the number is 10<var>a</var>+<var>b</var>, then 10<var>b</var>+<var>a</var> = 1.75(10<var>a</var>+<var>b</var>), so <var>b</var> = 2<var>a</var>: the numbers are 12, 24, 36, 48 — four of them.',
  'The sides add to 13 and multiply to 40: they are 5 and 8, difference 3.',
  'With <var>q</var> quarters, 25<var>q</var> + 5(15 &minus; <var>q</var>) = 215: <var>q</var> = 7.',
  'Each zero needs a 2&times;5 pair; fives are scarcer: they come from 5, 10, 15, 20, and 25 (which gives two), six in all.',
 ],
}
